services:
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    env_file:
      - .env
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/var/task
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
